.PHONY: version
version:
	$(MAKE) -C show-version

.PHONY: buffering
buffering:
	$(MAKE) -C buffering

.PHONY: multi-writer
multi-writer:
	$(MAKE) -C multi-writer

.PHONY: rand
rand:
	$(MAKE) -C rand

.PHONY: humanize
humanize:
	$(MAKE) -C humanize

.PHONY: exec
exec:
	$(MAKE) -C exec
