.PHONY: version
version:
	$(MAKE) -C show-version

.PHONY: buffering
buffering:
	cd buffering; make

.PHONY: multi-writer
multi-writer:
	cd multi-writer; make

.PHONY: rand
rand:
	cd rand; make

.PHONY: humanize
humanize:
	cd humanize; make

.PHONY: exec
exec:
	cd exec; make
