.DEFAULT_GOAL:= classical-type-assertion

.PHONY: classical-type-assertion
classical-type-assertion:
	$(MAKE) -C classical-type-assertion

.PHONY: reflect-value-of
reflect-value-of:
	$(MAKE) -C reflect-value-of

.PHONY: reflect-type
reflect-type:
	$(MAKE) -C reflect-type

.PHONY: dynamic-create
dynamic-create:
	$(MAKE) -C dynamic-create

.PHONY: reflect-scope-pkg
reflect-scope-pkg:
	$(MAKE) -C reflect-scope-pkg

.PHONY: reflect-can-set
reflect-can-set:
	$(MAKE) -C reflect-can-set

.PHONY: reflect-type-implements
reflect-type-implements:
	$(MAKE) -C reflect-type-implements

.PHONY: reflect-select-ch
reflect-select-ch:
	$(MAKE) -C select-ch
	$(MAKE) -C reflect-select-ch

.PHONY: reflect-access-performance
reflect-access-performance:
	$(MAKE) -C reflect-access-performance

.PHONY: reflect-sort-performance
reflect-sort-performance:
	$(MAKE) -C reflect-sort-performance
