.DEFAULT_GOAL:= classical-type-assertion

.PHONY: classical-type-assertion
classical-type-assertion:
	$(MAKE) -C classical-type-assertion

.PHONY: reflect-value-of
reflect-value-of:
	$(MAKE) -C reflect-value-of

.PHONY: reflect-type
reflect-type:
	$(MAKE) -C reflect-type

.PHONY: dynamic-create
dynamic-create:
	$(MAKE) -C dynamic-create
