.DEFAULT_GOAL:= join-filepath

.PHONY: join-filepath
join-filepath:
	$(MAKE) -C join-filepath

.PHONY: server-filepath
server-filepath:
	$(MAKE) -C server-filepath run-server

.PHONY: defer-release-file-handle
defer-release-file-handle:
	$(MAKE) -C defer-release-file-handle

.PHONY: compatible-color-tty
compatible-color-tty:
	$(MAKE) -C compatible-color-tty

.PHONY: load-config-file
load-config-file:
	$(MAKE) -C load-config-file
