.DEFAULT_GOAL:= exec

.PHONY: join-filepath
join-filepath:
	$(MAKE) -C join-filepath

.PHONY: server-filepath
server-filepath:
	$(MAKE) -C server-filepath run-server

.PHONY: defer-release-file-handle
defer-release-file-handle:
	$(MAKE) -C defer-release-file-handle
